# Train on CLA with EWC using with Fast-SCNN architecture pretrained on NYU.
network_params:
  architecture: fast_scnn
  freeze_encoder: true
  model_params:
    image_h: 480
    image_w: 640
  normalization_type: batch
training_params:
  batch_size: 10
  learning_rate: 0.00001
  num_training_epochs: 100
  perform_data_augmentation: false
  stopping_min_epoch: 50
  stopping_patience: 20
dataset_params:
  test_dataset: NyuDepthV2Labeled
  test_scene: null
  train_dataset: BfsegCLAMeshdistLabels
  train_scene: null
  validation_percentage: 10
logging_params:
  model_save_freq: 1
  exp_name: fast_scnn_from_nyu_to_cla_finetune_freeze_encoder
cl_params:
  cl_framework: finetune
  fraction_replay_ds_to_use: null
  # Note: this needs to be specified.
  pretrained_dir: null
  ratio_main_ds_replay_ds: null