# Train on CLA with EWC using with Fast-SCNN architecture pretrained on NYU.
network_params:
  architecture: fast_scnn
  freeze_encoder: false
  model_params:
    image_h: 480
    image_w: 640
  normalization_type: batch
training_params:
  batch_size: 10
  learning_rate: 0.00001
  num_training_epochs: 40
  stopping_patience: 100
dataset_params:
  test_dataset: NyuDepthV2Labeled
  test_scene: null
  train_dataset: MeshdistPseudolabels
  train_scene: null
  validation_percentage: 10
logging_params:
  model_save_freq: 1
  exp_name: fast_scnn_from_nyu_to_rumlang_finetune
cl_params:
  cl_framework: finetune
  # Note: this needs to be specified.
  pretrained_dir: null
  # /home/matthias/.keras/datasets/1Wu1p2U7BgK8TwzvTdLlBWCemo3oPN-ad.h5