# Finetune on Rumlang with replay from NYU and CLA.
network_params:
  architecture: fast_scnn
  freeze_encoder: false
  model_params:
    image_h: 480
    image_w: 640
  normalization_type: group
training_params:
  batch_size: 10
  learning_rate: 0.00001
  num_training_epochs: 100
  perform_data_augmentation: true
  stopping_min_epoch: 50
  stopping_patience: 20
dataset_params:
  replay_datasets:
    - NyuDepthV2Labeled
    - BfsegCLAMeshdistLabels
  replay_datasets_scene:
    - null
    - null
  test_dataset: null
  test_scene: null
  train_dataset: MeshdistPseudolabels
  train_scene: null
  validation_percentage: 10
logging_params:
  model_save_freq: 1
  exp_name: fast_scnn_from_nyu_to_cla_to_rumlang_finetune_ratio_replay
cl_params:
  cl_framework: finetune
  fraction_replay_ds_to_use: null
  # Note: this needs to be specified.
  pretrained_dir: NEED_TO_SPECIFY_THIS
  ratio_main_ds_replay_ds:
    - 1
    - 1
    - 1