# Training from scratch on scene 2 from Rumlang.
network_params:
  architecture: fast_scnn
  freeze_encoder: false
  model_params:
    image_h: 480
    image_w: 640
  normalization_type: group
training_params:
  batch_size: 10
  learning_rate: 0.0001
  num_training_epochs: 100
  perform_data_augmentation: true
  reduce_lr_on_plateau: true
  stopping_min_epoch: 50
  stopping_patience: 20
  use_balanced_loss: false
dataset_params:
  replay_datasets: null
  replay_datasets_scene: null
  test_dataset: MeshdistPseudolabels
  test_scene: rumlang3
  train_dataset: MeshdistPseudolabels
  train_scene: rumlang2
  validation_percentage: 10
logging_params:
  model_save_freq: 1
  exp_name: pretrain_rumlang_scene2
cl_params:
  cl_framework: finetune
  fraction_replay_ds_to_use: null
  pretrained_dir: null
  ratio_main_ds_replay_ds: null
