# Train on CLA with finetuning using Fast-SCNN architecture pretrained on NYU.
network_params:
  architecture: fast_scnn
  freeze_encoder: false
  model_params:
    image_h: 480
    image_w: 640
  normalization_type: group
training_params:
  batch_size: 10
  learning_rate: 0.00001
  num_training_epochs: 250
  perform_data_augmentation: true
  reduce_lr_on_plateau: true
  stopping_min_epoch: 50
  stopping_patience: 20
  use_balanced_loss: false
dataset_params:
  replay_datasets: null
  replay_datasets_scene: null
  test_dataset: null
  test_scene: null
  train_dataset: MeshdistPseudolabelsSparse1
  train_scene: office6_sparse50_all
  validation_percentage: 5
logging_params:
  model_save_freq: 1
  exp_name: office6_sparse50_all_finetune
cl_params:
  cl_framework: finetune
  fraction_replay_ds_to_use: null
  # Note: this needs to be specified.
  pretrained_dir: /home/xavier/.keras/datasets/1Wu1p2U7BgK8TwzvTdLlBWCemo3oPN-ad
  ratio_main_ds_replay_ds: null