# Train on CLA with finetuning using Fast-SCNN architecture pretrained on NYU.
network_params:
  architecture: fast_scnn
  freeze_encoder: false
  model_params:
    image_h: 480
    image_w: 640
  normalization_type: group
training_params:
  batch_size: 10
  learning_rate: 0.0001
  num_training_epochs: 250
  perform_data_augmentation: true
  perform_preprocessing: false
  reduce_lr_on_plateau: true
  stopping_min_epoch: 50
  stopping_patience: 20
  use_balanced_loss: false
dataset_params:
  replay_datasets: 
    - NyuDepthV2Labeled
  replay_datasets_scene: 
    - null
  test_dataset: null
  test_scene: null
  train_dataset: MeshdistPseudolabelsDense
  train_scene: office3_combined2050_dyn_cam2
  validation_percentage: 5
logging_params:
  model_save_freq: 1
  exp_name: office3_combined2050_dyn_cam2_finetune
cl_params:
  cl_framework: finetune
  fraction_replay_ds_to_use: 0.1
  # Note: this needs to be specified.
  pretrained_dir: /xavier_ssd/saved_weights/nyu_pretrained_weights_10.h5
  ratio_main_ds_replay_ds: null
